default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>

development:
  database: rubyci_homepage_development
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000  

test:
  <<: *default
  database: rubyci_homepage_test

production:
  <<: *default
  url: <%= ENV['POSTGRES_URL'] %>
